# Generated by Django 3.1.6 on 2021-02-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='section',
            field=models.IntegerField(default=0),
        ),
    ]
