# Generated by Django 3.1.6 on 2021-02-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('DRK', 'Drink'), ('DNR', 'Dinner'), ('LCH', 'Lunch')], default='choose', max_length=3),
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(default='Description', max_length=300),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='Name', max_length=30),
        ),
    ]
