# Generated by Django 3.1.6 on 2021-02-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210201_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Drink', 'Drink'), ('Dinner', 'Dinner'), ('Lunch', 'Lunch')], default='choose', max_length=6),
        ),
    ]
